### ISSUE TITLE
problem: bidders cannot settle final payment on other chains

### ISSUE THREAD

**Issue by gazhayes** [trofimarket/problems#17]
problem: bidders cannot settle final payment on other chains

solution: change the way we do payments and do it like this instead:

1. Take the merchant's platform tax. This is the amount that users must lock (as a deposit) in order to bid. For example if the platform tax is 1% and the user bids 1 BTC, they need to lock 0.01BTC (on BSC), can be in BNB, wBTC, wETH, whatever is already implemented in the SC. This is unlocked if they are outbid. 

The SC does not need to track the total bid amount, just the deposit amount (in BTC). The UI can simply calculate what the total bid actually is, based on the deposit amount and the platform tax. So if a user locks 10 ETH in a bid, and chainlink says that this is 0.5546 BTC at the time, and the merchant's tax rate is 1%, then the bid shown in the UI will be 55.46BTC. If that bid wins the auction, then the winner must pay the merchant 55.46-0.5546 = 54.9054 BTC or equivalent. 

2. When setting up their account, merchants must input addresses for final settlement on: BSC chain, ETH chain, Bitcoin chain. This should be stored in the auction object so that users can verify not only through the app but through block explorer.

3. The user pays final settlement directly to the merchant's wallet. Our SC does not need to know about it.

4. The merchant releases the NFT to the bidder once final settlement has been made, or they can restart the auction if payment is not made within 24 hours.

5. Regardless of the outcome, the platform tax goes to the platform at the end of the auction.

**Comment by ssomraaj** [comment]
@gazhayes this feature is added for auction

**Comment by ExcessionAtEsperi** [comment]
@ssomraaj 

problem: the deposit amount has not been deducted from the final settlement amount
problem: UI should be BTC not USD

<img width="445" alt="Screenshot 2021-07-12 at 3 19 18 PM" src="https://user-images.githubusercontent.com/35320726/125246585-8daa2d00-e324-11eb-8d9a-a66ab809c262.png">

**Comment by ExcessionAtEsperi** [comment]
@ssomraaj  Have you implemented the merchant's approval part yet?

**Comment by ssomraaj** [comment]
yes the merchant can settle @ExcessionAtEsperi and also I'll update the other two stuff

**Comment by ssomraaj** [comment]
@gazhayes and @ExcessionAtEsperi any comments on this ?

**Comment by ssomraaj** [comment]
@ExcessionAtEsperi https://github.com/trofimarket/znft-client/pull/12
