### ISSUE TITLE
Problem: profits aren't distributed to shareholders

### ISSUE THREAD

**Issue by gazhayes** [trofimarket/problems#21]
Problem: profits aren't distributed to shareholders

Solution: 
Allow any shareholder to propose a payout of the profits (platform tax and listing fees). This proposal must include a list of addresses and the amount to pay (currency + amount). Amounts must add up to <= total available.

In order for the payout to be processed, >60% of shareholders must vote yes, and <5% must vote no. Vote must be active for at least 24 hours to give time for people to vote no.

**Comment by ssomraaj** [comment]
how to handle multiple assets ?

**Comment by ssomraaj** [comment]
Fixed in https://github.com/trofimarket/znft-client/pull/16

**Comment by ssomraaj** [comment]
@ExcessionAtEsperi & @gazhayes, if this is completed please close this issue

**Comment by samuelralak** [comment]
hey @ssomraaj can't seem to be able to create a new company, any idea whats going on? 

Getting the below error from console.
![Screenshot 2021-07-19 at 15 55 09](https://user-images.githubusercontent.com/4476552/126162834-9b4f67d4-40ba-480a-a693-f10d5be935bd.png)

Need help verifying this on your side, if so I can go ahead and create a new issue asap

**Comment by ssomraaj** [comment]
@samuelralak have updated the .env and .env.development files ? and the ABI ?

**Comment by samuelralak** [comment]
@ssomraaj no sir, pulling the latest from master now

**Comment by ssomraaj** [comment]
is this on your localhost @samuelralak?

**Comment by samuelralak** [comment]
@ssomraaj yes its on my localhost, pulled the latest and still getting the same issue

**Comment by ssomraaj** [comment]
I'm checking it please give me a few minutes @samuelralak

**Comment by ssomraaj** [comment]
@samuelralak it's working for me. can you double-check https://github.com/trofimarket/znft-client
