### ISSUE TITLE
Problem: can't list NFT for sale

### ISSUE THREAD

**Issue by ExcessionAtEsperi** [trofimarket/problems#33]
Can't list NFT for sale
Using address 0x1cACF205797B0A288EA8f111Ab211A6E43baEd5e

https://user-images.githubusercontent.com/35320726/124693177-8d1f2a00-df11-11eb-8f55-418f0aa24258.mp4

**Comment by ssomraaj** [comment]
@ExcessionAtEsperi can you please check again this issue ?
