### ISSUE TITLE
Problem: Existing merchants can still apply again

### ISSUE THREAD

**Issue by ExcessionAtEsperi** [trofimarket/problems#37]
Problem: Existing merchants can still apply again

Very confusing for existing merchants

solution: disable this form for existing merchants

<img width="913" alt="Screenshot 2021-07-12 at 11 20 09 AM" src="https://user-images.githubusercontent.com/35320726/125226177-26c84c00-e303-11eb-9946-330368dc5062.png">

**Comment by ssomraaj** [comment]
ok will do

**Comment by ssomraaj** [comment]
@ExcessionAtEsperi this is fixed
